# travis-ci.com is currently not used,
# and this file may be outdated.
#
# GitHub Actions are used:
# configured via the files in the directory:
# `.github/workflows/`
git:
  depth: 3

language: python

python:
  - "3.9"
  - "3.10"

addons:
  apt:
    packages:
      - cflow
      - graphviz

install:
  - pip install --upgrade pip setuptools
  # pycflow2dot
  - pip install .

script:
  - cd tests/
  - make all
